# permissions for end users to view simplemongodbcommunities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplemongodbcommunity-viewer-role
rules:
- apiGroups:
  - mongodbcommunity.mongodb.com
  resources:
  - simplemongodbcommunities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mongodbcommunity.mongodb.com
  resources:
  - simplemongodbcommunities/status
  verbs:
  - get
